version: 2

jobs:
  build:
    docker:
      - image: zopnow/lamp-stack
    working_directory: /var/www/application
    steps:
      - run:
          name: Running selenium standalone
          command: |
            cd ~/selenium
            xvfb-run java -jar selenium-server-standalone-3.4.0.jar
            sleep 5
          background: true
      - run: rm -rf /var/www/application
      - checkout
      - run: npm install
      - run: npm run build
      - run: a2enmod headers
      - run: service apache2 restart
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      # - run: ./vendor/bin/codecept build
      # - run: ./vendor/bin/codecept run
      - deploy:
          name: Deploy Application
          command: |
            npm install -g firebase-tools
            if [ "${CIRCLE_BRANCH}" == “master” ]; then
              firebase deploy --token=$FIREBASE_TOKEN --non-interactive
            fi
      - run:
          name: End script
          command: echo Script completed
