version: 2

jobs:
  build:
    docker:
      - image: codeception/codeception
    working_directory: /var/www/application
    steps:
      # - run:
      #     name: Fetching selenium webdriver
      #     command: |
      #       mkdir ~/selenium
      #       cd ~/selenium
      #       wget https://chromedriver.storage.googleapis.com/2.34/chromedriver_linux64.zip
      #       unzip chromedriver_linux64.zip
      #       wget http://selenium-release.storage.googleapis.com/3.8/selenium-server-standalone-3.8.1.jar
      #       apt-get install libxi6 libgconf-2-4 -y
      # - run:
      #     name: Running selenium standalone
      #     command: |
      #       cd ~/selenium
      #       xvfb-run java -jar ~/selenium/selenium-server-standalone-3.8.1.jar
      #       sleep 10
      #     background: true
      - run: rm -rf /var/www/application
      - checkout
      - run: npm install
      - run: npm run build
      - run: a2enmod headers
      - run: service apache2 restart
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: ./vendor/bin/codecept build
      - run: ./vendor/bin/codecept run
      - deploy:
          name: Deploy Application
          command: |
            if [ "${CIRCLE_BRANCH}" == “master” ]; then
              firebase deploy --token=$FIREBASE_TOKEN --non-interactive
            fi
      - run:
          name: End script
          command: echo Script completed
